### PR TITLE
practice pull request

### PR DESCRIPTION
**Pull request by yujiazhang84**

### CODE REVIEW

**Comment by JoeLaviano** [comment]
Should this be a .py file instead of a .html file?

**Comment by rwest** [comment]
Yes - we noticed and fixed this after class. I suggest you close this PR @JoeLaviano, and @yujiazhang84 can open a new one with the `.py` file.

**Comment by yujiazhang84** [comment]
@JoeLaviano Yes, something went wrong when I was converting notebook to script. Thank you for pointing it out. @rwest Can I just close this pull request from my side? Or will it discard the previous request if I create a new one? (I will also google it myself)

**Comment by JoeLaviano** [comment]
@yujiazhang84 @rwest closing this one now! I'll get notified if you request another I'm sure.

**Pull request closed without merging**
